name: InstallTest

on: [push]

jobs:
  ubuntu-bash:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    steps:
      - name: Install required packages
        run: apt-get update && apt-get install -y git curl
        # Faithfully reproduce the installation method in README
      - name: Clone
        run: git clone https://github.com/yuta100101/dotfiles.git -b ${{ github.ref_name }}
      - name: Install dotfiles
        run: dotfiles/install.sh bash
      - name: Activate
        run: source ~/.bashrc
  ubuntu-fish:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    steps:
      - name: Install required packages
        run: apt-get update && apt-get install -y git curl sudo
        # Faithfully reproduce the installation method in README
      - name: Clone
        run: git clone https://github.com/yuta100101/dotfiles.git -b ${{ github.ref_name }}
      - name: Install dotfiles
        run: dotfiles/install.sh fish