name: InstallTest

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    steps:
      - name: Install required packages
        run: apt-get update && apt-get install -y git curl
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: recursive
      - name: Install dotfiles
        run: ./install.sh
      - name: Activate
        run: source ~/.bashrc